version: 2
updates:
  # maintain dependencies for GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly" # default = monday
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github_actions"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "java"
    ignore:
      - dependency-name: "org.eclipse.edc:*"

