[metadata]
format.version = "1.1"

[versions]
aws = "2.47.1"
edc = "1.0.0-SNAPSHOT"

[libraries]
edc-junit = { module = "org.eclipse.edc:junit", version.ref = "edc" }
edc-spi-core = { module = "org.eclipse.edc:core-spi", version.ref = "edc" }

# AWS dependencies
aws-secretsmanager = { module = "software.amazon.awssdk:secretsmanager", version.ref = "aws" }

[plugins]
edc-build = { id = "org.eclipse.edc.edc-build", version = "1.5.2" }
