name: "Bump version in gradle.properties"
description: "Increments the patch version of the version found in gradle.properties, appends -SNAPSHOT"
inputs:
  target_branch:
    default: 'main'
    description: "Branch on which the version bump is to be done."
    required: false
  base_version:
    description: "The current version, which is to be bumped to the next snapshot"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: read version from gradle.properties
      shell: bash
      run: |
        # Prepare git env
        git config user.name "eclipse-edc-bot"
        git config user.email "edc-bot@eclipse.org"

        # checkout target
        git fetch origin
        git checkout ${{ inputs.target_branch }}

        # use current version from input
        oldVersion=${{ inputs.base_version }}
        if [ -z $oldVersion ]; then
          #... or read it from gradle.properties
          echo "No base_version input was given, will read base version from gradle.properties"
          oldVersion=$(grep "version" gradle.properties  | awk -F= '{print $2}')
        fi      
        
        # read the major, minor, and patch components, consume -SNAPSHOT
        IFS=.- read -r RELEASE_VERSION_MAJOR RELEASE_VERSION_MINOR RELEASE_VERSION_PATCH SNAPSHOT<<<"$oldVersion"
        INC=0
        # Compute new snapshot version, do not increment snapshot on non-final releases, e.g. -rc1
        if [ -z $SNAPSHOT ]; then
          echo "$oldVersion is a final release version, increase patch for next snapshot"
          INC=1
        else
          echo "$oldVersion is not a final release version (contains \"$SNAPSHOT\"), will not increase patch"
        fi

        # construct the new version
        newVersion="$RELEASE_VERSION_MAJOR.$RELEASE_VERSION_MINOR.$((RELEASE_VERSION_PATCH+$INC))"-SNAPSHOT

        # replace every occurrence of =$oldVersion with =$newVersion
        grep -rlz "$oldVersion" . --exclude=\*.{sh,bin} | xargs sed -i "s/$oldVersion/$newVersion/g"

        echo "Bumped the version from $oldVersion to $newVersion"

        # Commit and push to the desired branch, defaults to 'main'
        git add .
        git commit --message "Bump version from $oldVersion to $newVersion [skip ci]"

        git push origin ${{ inputs.target_branch }}
