# this workflow is only for testing and will be removed later!

name: Test Repo Split workflows

on:
  workflow_dispatch:
    inputs:
      version:
        description: Semantic Version string to use for this nightly build
        required: false

env:
  INPUT_VERSION: ${{ github.event.inputs.version || inputs.version }}


#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true

jobs:
  Determine-Version:
    # this looks to be necessary because some constructs as "with" are not able to get values from env
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get-version.outputs.VERSION }}
    steps:
      - name: "Extract version"
        id: get-version
        run: echo "VERSION=${{ env.INPUT_VERSION }}" >> "$GITHUB_OUTPUT"

  publish:
    uses: paullatzelsperger/.github-edc/.github/workflows/publish-technology.yaml@main
    needs: [Determine-Version]
    with:
      version: ${{ needs.Determine-Version.outputs.VERSION }}
      component_release_workflow_file: "release-tech-aws.yaml"
      component_test_workflow_file: "verify.yaml"
    secrets: inherit