name: "Publish Snapshot Build"

on:
  push:
    branches:
      - main

jobs:
  Publish-Snapshot:
    # This workflow will abort if the required secrets don't exist
    uses: eclipse-edc/.github/.github/workflows/publish-snapshot.yml@main
    secrets: inherit
